#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.1 effective-5.10 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
#ifndef DRAGONCOPILOTTURNKEY_SWIFT_H
#define DRAGONCOPILOTTURNKEY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DragonCopilotTurnkey",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class ClientTokenProvider;
/// Protocol for a class that provides a valid access token for the Turnkey SDK.
/// \param scopes Optional scope string for token generation (default is nil).
///
/// \param forceRefresh Boolean indicating whether to force refresh the token (default is false).
///
/// \param onSuccess Callback that returns the <code>ClientTokenProvider</code> if the token is successfully retrieved.
///
/// \param onFailure Callback that returns an error if token retrieval fails.
///
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey22AppAccessTokenProvider_")
@protocol AppAccessTokenProvider
- (void)accessTokenWithScopes:(NSArray<NSString *> * _Nullable)scopes forceRefresh:(BOOL)forceRefresh onSuccess:(void (^ _Nonnull)(ClientTokenProvider * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(NSError * _Nonnull))onFailure;
@end

/// Protocol defining dictation-related events that clients can implement
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey20AppDictationDelegate_")
@protocol AppDictationDelegate
@optional
/// Called when dictation starts
- (void)dictationStarted;
/// Called when dictation stops
- (void)dictationStopped;
@end

/// Protocol defining internal client events that internal clients can implement
/// This is only available for internal Microsoft clients and provides access to SDK internal telemetry and diagnostic events
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey19AppInternalDelegate_")
@protocol AppInternalDelegate
@optional
/// Called when SDK telemetry data is available
/// \param eventName The name/type of the telemetry event
///
/// \param eventData Dictionary containing the telemetry event data
///
- (void)telemetryEventWithEventName:(NSString * _Nonnull)eventName eventData:(NSDictionary<NSString *, id> * _Nonnull)eventData;
/// Called when SDK diagnostic information is available
/// \param diagnosticType The type of diagnostic event
///
/// \param diagnosticData Dictionary containing the diagnostic data
///
- (void)diagnosticEventWithDiagnosticType:(NSString * _Nonnull)diagnosticType diagnosticData:(NSDictionary<NSString *, id> * _Nonnull)diagnosticData;
/// Called when SDK internal state changes
/// \param stateChange Description of the state change
///
/// \param newState The new state value
///
- (void)internalStateChangedWithStateChange:(NSString * _Nonnull)stateChange newState:(NSString * _Nonnull)newState;
@end

enum RecordingStopReason : NSInteger;
enum RecordingProgressNotification : NSInteger;
/// Protocol defining recording-related events that clients can implement
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey20AppRecordingDelegate_")
@protocol AppRecordingDelegate
@optional
/// Called when recording starts successfully
- (void)recordingStarted;
/// Called when recording fails to start
- (void)recordingFailed;
/// Called when recording stops
- (void)recordingStopped;
/// Called when recording is interrupted and automatically stopped
/// \param reason The reason why recording was automatically stopped
///
- (void)recordingInterruptedWithReason:(enum RecordingStopReason)reason;
/// Called when a notification or warning occurs during recording
/// \param notification The type of notification or warning
///
- (void)recordingNotificationWithNotification:(enum RecordingProgressNotification)notification;
@end

/// Protocol defining settings-related events that clients can implement
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey19AppSettingsDelegate_")
@protocol AppSettingsDelegate
@optional
/// Called when the screen-on-while-recording setting changes
/// \param screenOn Indicates whether the screen should stay on while recording
///
- (void)isIdleTimerDisabledWithIsOn:(BOOL)screenOn;
/// Called when the appearance theme changes
/// \param uiTheme The new theme identifier
///
- (void)appearanceThemeChangedTo:(NSString * _Nonnull)uiTheme;
/// Called when the application language needs to be changed
/// \param languageCode Indicates configured UI or Application Locale value. Example: “en-US”, “es-US”
///
- (void)applicationLanguageChangedTo:(NSString * _Nonnull)languageCode;
@end

enum SignOutReason : NSInteger;
/// Protocol defining events for the TurnKey framework that clients can implement
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey13AppUiDelegate_")
@protocol AppUiDelegate
@optional
/// Called when the WebView finishes loading
/// \param isLoadingDone Indicates whether the web view has finished loading
///
- (void)webViewLoaded:(BOOL)isLoadingDone;
/// Notifies when a logout occurs
/// \param logoutType The reason for the logout (user initiated, inactivity, navigate away, or environment change)
///
- (void)logoutWith:(enum SignOutReason)logoutType;
@end

@class UIViewController;
SWIFT_CLASS("_TtC20DragonCopilotTurnkey27AppWebViewControllerWrapper")
@interface AppWebViewControllerWrapper : NSObject
- (UIViewController * _Nonnull)getViewController SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol ConfigurationProvider;
@protocol SessionDataProvider;
SWIFT_CLASS("_TtC20DragonCopilotTurnkey17ApplicationConfig")
@interface ApplicationConfig : NSObject
+ (ApplicationConfig * _Nonnull)getInstanceWithDataProvider:(id <ConfigurationProvider> _Nonnull)dataProvider delegate:(id <AppUiDelegate> _Nullable)delegate recordingDelegate:(id <AppRecordingDelegate> _Nullable)recordingDelegate dictationDelegate:(id <AppDictationDelegate> _Nullable)dictationDelegate settingsDelegate:(id <AppSettingsDelegate> _Nullable)settingsDelegate internalClientDelegate:(id <AppInternalDelegate> _Nullable)internalClientDelegate SWIFT_WARN_UNUSED_RESULT;
+ (void)clearInstance;
- (UIViewController * _Nonnull)openSessionControllerWithSessionDataProvider:(id <SessionDataProvider> _Nonnull)sessionDataProvider SWIFT_WARN_UNUSED_RESULT;
- (void)closeSession;
- (void)disableLogging;
- (void)developerModeWithIsON:(BOOL)isON;
+ (BOOL)isDeveloperModeOn SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ClientAppInfo;
@class ServerInfo;
enum AuthType : NSInteger;
@class UserInfo;
/// Configuration for the Turnkey SDK
SWIFT_CLASS("_TtC20DragonCopilotTurnkey25ApplicationConfigProvider")
@interface ApplicationConfigProvider : NSObject
/// Initializes a new instance of `ApplicationConfigProvider
- (nonnull instancetype)initWithClientAppInfo:(ClientAppInfo * _Nonnull)clientAppInfo serverInfo:(ServerInfo * _Nonnull)serverInfo providerName:(NSString * _Nonnull)providerName isInternalClient:(BOOL)isInternalClient authType:(enum AuthType)authType userInfo:(UserInfo * _Nullable)userInfo partnerId:(NSString * _Nullable)partnerId customerId:(NSString * _Nullable)customerId ehrInstanceId:(NSString * _Nullable)ehrInstanceId productId:(NSString * _Nullable)productId traceId:(NSString * _Nullable)traceId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Authentication type for the SDK
typedef SWIFT_ENUM(NSInteger, AuthType, open) {
  AuthTypeEntraId = 0,
  AuthTypePartnerToken = 1,
  AuthTypeSmartOnFhir = 2,
};

SWIFT_CLASS("_TtC20DragonCopilotTurnkey13ClientAppInfo")
@interface ClientAppInfo : NSObject
/// Initializes a new instance of <code>ClientAppInfo</code>.
- (nonnull instancetype)initWithAppId:(NSString * _Nullable)appId appVersion:(NSString * _Nullable)appVersion deviceId:(NSString * _Nullable)deviceId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Base class for token responses used in the Turnkey SDK.
/// \param token The access token string.
///
SWIFT_CLASS("_TtC20DragonCopilotTurnkey11ClientToken")
@interface ClientToken : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull token;
- (nonnull instancetype)initWithToken:(NSString * _Nonnull)token OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDate;
/// Token response for Entra authentication.
/// \param token The access token string.
///
/// \param expireOn The expiration date of the token.
///
/// \param scope Optional OAuth scopes for the token.
///
/// \param tenantId Optional Azure AD tenant identifier.
///
SWIFT_CLASS("_TtC20DragonCopilotTurnkey16ClientEntraToken")
@interface ClientEntraToken : ClientToken
@property (nonatomic, readonly, copy) NSDate * _Nonnull expireOn;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable scope;
@property (nonatomic, readonly, copy) NSString * _Nullable tenantId;
- (nonnull instancetype)initWithToken:(NSString * _Nonnull)token expireOn:(NSDate * _Nonnull)expireOn scope:(NSArray<NSString *> * _Nullable)scope tenantId:(NSString * _Nullable)tenantId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithToken:(NSString * _Nonnull)token SWIFT_UNAVAILABLE;
@end

/// Token response for SMART on FHIR (SoF) authentication.
/// Contains only the SMART launch parameters (issuer and launch).
/// The OAuth token is provided separately via ClientToken.
/// \param issuer The issuer URL for SMART on FHIR authentication.
///
/// \param launch The launch code for SMART on FHIR authentication.
///
SWIFT_CLASS("_TtC20DragonCopilotTurnkey14ClientSoFToken")
@interface ClientSoFToken : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull issuer;
@property (nonatomic, readonly, copy) NSString * _Nonnull launch;
- (nonnull instancetype)initWithIssuer:(NSString * _Nonnull)issuer launch:(NSString * _Nonnull)launch OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Container class to hold different types of authentication responses.
SWIFT_CLASS("_TtC20DragonCopilotTurnkey19ClientTokenProvider")
@interface ClientTokenProvider : NSObject
@property (nonatomic, readonly, strong) ClientToken * _Nullable clientToken;
@property (nonatomic, readonly, strong) ClientEntraToken * _Nullable clientEntraToken;
@property (nonatomic, readonly, strong) ClientSoFToken * _Nullable clientSoFToken;
/// Initializes the container with optional responses.
/// For SMART on FHIR, both clientToken (OAuth token) and clientSoFToken (SMART params) should be provided.
/// \param clientToken An instance of <code>ClientToken</code> or nil.
///
/// \param clientEntraToken An instance of <code>ClientEntraToken</code> or nil.
///
/// \param clientSoFToken An instance of <code>ClientSoFToken</code> or nil.
///
- (nonnull instancetype)initWithClientToken:(ClientToken * _Nullable)clientToken clientEntraToken:(ClientEntraToken * _Nullable)clientEntraToken clientSoFToken:(ClientSoFToken * _Nullable)clientSoFToken OBJC_DESIGNATED_INITIALIZER;
/// Convenience initializer for <code>ClientToken</code>.
/// \param clientToken An instance of <code>ClientToken</code>.
///
- (nonnull instancetype)initWithClientToken:(ClientToken * _Nonnull)clientToken;
/// Convenience initializer for <code>ClientEntraToken</code>.
/// \param clientEntraToken An instance of <code>ClientEntraToken</code>.
///
- (nonnull instancetype)initWithClientEntraToken:(ClientEntraToken * _Nonnull)clientEntraToken;
/// Convenience initializer for <code>ClientSoFToken</code>.
/// \param clientSoFToken An instance of <code>ClientSoFToken</code>.
///
- (nonnull instancetype)initWithClientSoFToken:(ClientSoFToken * _Nonnull)clientSoFToken;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Protocol for providing configuration data to the TurnKey framework
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey21ConfigurationProvider_")
@protocol ConfigurationProvider
/// Returns the configuration for the TurnKey framework
///
/// returns:
/// The configuration object
- (ApplicationConfigProvider * _Nonnull)getConfiguration SWIFT_WARN_UNUSED_RESULT;
/// Returns the access token provider for authentication
///
/// returns:
/// The access token provider
- (id <AppAccessTokenProvider> _Nonnull)getAccessTokenProvider SWIFT_WARN_UNUSED_RESULT;
/// Returns the user information
///
/// returns:
/// The user object
- (UserInfo * _Nonnull)getUserInfo SWIFT_WARN_UNUSED_RESULT;
@end

/// Represents details for a patient.
SWIFT_CLASS("_TtC20DragonCopilotTurnkey11PatientInfo")
@interface PatientInfo : NSObject
/// Initializes a new instance of <code>PatientInfo</code>.
- (nonnull instancetype)initWithId:(NSString * _Nullable)id fhirId:(NSString * _Nullable)fhirId firstName:(NSString * _Nullable)firstName lastName:(NSString * _Nullable)lastName middleName:(NSString * _Nullable)middleName gender:(NSString * _Nullable)gender birthDate:(NSDate * _Nullable)birthDate medicalRecordNumber:(NSString * _Nullable)medicalRecordNumber OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents different notifications and warnings during recording
typedef SWIFT_ENUM(NSInteger, RecordingProgressNotification, open) {
/// Warning that recording duration limit is approaching
  RecordingProgressNotificationReachedWarnLimit = 0,
/// Audio silence detected during recording
  RecordingProgressNotificationAudioLoss = 1,
/// External audio device detected
  RecordingProgressNotificationExternalAudioDeviceDetected = 2,
};

/// Represents the different reasons why a recording might be stopped
typedef SWIFT_ENUM(NSInteger, RecordingStopReason, open) {
/// User manually stopped recording
  RecordingStopReasonUser = 0,
/// Recording automatically stopped due to a system error
  RecordingStopReasonSystemError = 1,
/// Recording automatically stopped due to audio interruption (e.g., phone call)
  RecordingStopReasonAudioInterrupted = 2,
/// Recording automatically stopped because maximum duration was reached
  RecordingStopReasonReachedMaxLimit = 3,
/// Recording automatically stopped due to incompatible audio device detected
  RecordingStopReasonIncompatibleInputDevice = 4,
/// Recording automatically stopped due to audio device change
  RecordingStopReasonAudioDeviceChanged = 5,
};

/// SDK-level constants for default configuration values
SWIFT_CLASS("_TtC20DragonCopilotTurnkey12SDKConstants")
@interface SDKConstants : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC20DragonCopilotTurnkey10ServerInfo")
@interface ServerInfo : NSObject
/// Initializes a new instance of <code>ServerInfo</code>.
- (nonnull instancetype)initWithEnvironment:(NSString * _Nullable)environment geography:(NSString * _Nullable)geography cloudInstance:(NSString * _Nullable)cloudInstance OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class VisitInfo;
/// Protocol for providing session data to the TurnKey framework
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey19SessionDataProvider_")
@protocol SessionDataProvider
/// Returns the patient information for the current session
///
/// returns:
/// The patient object
- (PatientInfo * _Nonnull)getPatientInfo SWIFT_WARN_UNUSED_RESULT;
/// Returns the visit information for the current session
///
/// returns:
/// The visit object
- (VisitInfo * _Nonnull)getVisitInfo SWIFT_WARN_UNUSED_RESULT;
@end

/// Represents the reason for user logout from the TurnKey framework
typedef SWIFT_ENUM(NSInteger, SignOutReason, open) {
/// User initiated logout
  SignOutReasonUser = 0,
/// Logout due to inactivity timeout
  SignOutReasonInactivity = 1,
/// Logout due to navigation away from the app
  SignOutReasonNavigateAway = 2,
/// Logout due to environment change
  SignOutReasonEnvironmentChange = 3,
/// Logout due to authentication failure
  SignOutReasonAuthenticationFailed = 4,
};

/// Represents details for a user or practitioner.
SWIFT_CLASS("_TtC20DragonCopilotTurnkey8UserInfo")
@interface UserInfo : NSObject
/// Initializes a new instance of <code>UserInfo</code>.
- (nonnull instancetype)initWithId:(NSString * _Nullable)id fhirId:(NSString * _Nullable)fhirId firstName:(NSString * _Nullable)firstName middleName:(NSString * _Nullable)middleName lastName:(NSString * _Nullable)lastName ehrUserId:(NSString * _Nullable)ehrUserId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents details of a visit.
SWIFT_CLASS("_TtC20DragonCopilotTurnkey9VisitInfo")
@interface VisitInfo : NSObject
/// Initializes a new instance of <code>VisitInfo</code>.
- (nonnull instancetype)initWithId:(NSString * _Nullable)id fhirId:(NSString * _Nullable)fhirId correlationId:(NSString * _Nullable)correlationId metadata:(NSString * _Nullable)metadata reasonForVisit:(NSString * _Nullable)reasonForVisit OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.1 effective-5.10 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
#ifndef DRAGONCOPILOTTURNKEY_SWIFT_H
#define DRAGONCOPILOTTURNKEY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DragonCopilotTurnkey",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class ClientTokenProvider;
/// Protocol for a class that provides a valid access token for the Turnkey SDK.
/// \param scopes Optional scope string for token generation (default is nil).
///
/// \param forceRefresh Boolean indicating whether to force refresh the token (default is false).
///
/// \param onSuccess Callback that returns the <code>ClientTokenProvider</code> if the token is successfully retrieved.
///
/// \param onFailure Callback that returns an error if token retrieval fails.
///
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey22AppAccessTokenProvider_")
@protocol AppAccessTokenProvider
- (void)accessTokenWithScopes:(NSArray<NSString *> * _Nullable)scopes forceRefresh:(BOOL)forceRefresh onSuccess:(void (^ _Nonnull)(ClientTokenProvider * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(NSError * _Nonnull))onFailure;
@end

/// Protocol defining dictation-related events that clients can implement
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey20AppDictationDelegate_")
@protocol AppDictationDelegate
@optional
/// Called when dictation starts
- (void)dictationStarted;
/// Called when dictation stops
- (void)dictationStopped;
@end

/// Protocol defining internal client events that internal clients can implement
/// This is only available for internal Microsoft clients and provides access to SDK internal telemetry and diagnostic events
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey19AppInternalDelegate_")
@protocol AppInternalDelegate
@optional
/// Called when SDK telemetry data is available
/// \param eventName The name/type of the telemetry event
///
/// \param eventData Dictionary containing the telemetry event data
///
- (void)telemetryEventWithEventName:(NSString * _Nonnull)eventName eventData:(NSDictionary<NSString *, id> * _Nonnull)eventData;
/// Called when SDK diagnostic information is available
/// \param diagnosticType The type of diagnostic event
///
/// \param diagnosticData Dictionary containing the diagnostic data
///
- (void)diagnosticEventWithDiagnosticType:(NSString * _Nonnull)diagnosticType diagnosticData:(NSDictionary<NSString *, id> * _Nonnull)diagnosticData;
/// Called when SDK internal state changes
/// \param stateChange Description of the state change
///
/// \param newState The new state value
///
- (void)internalStateChangedWithStateChange:(NSString * _Nonnull)stateChange newState:(NSString * _Nonnull)newState;
@end

enum RecordingStopReason : NSInteger;
enum RecordingProgressNotification : NSInteger;
/// Protocol defining recording-related events that clients can implement
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey20AppRecordingDelegate_")
@protocol AppRecordingDelegate
@optional
/// Called when recording starts successfully
- (void)recordingStarted;
/// Called when recording fails to start
- (void)recordingFailed;
/// Called when recording stops
- (void)recordingStopped;
/// Called when recording is interrupted and automatically stopped
/// \param reason The reason why recording was automatically stopped
///
- (void)recordingInterruptedWithReason:(enum RecordingStopReason)reason;
/// Called when a notification or warning occurs during recording
/// \param notification The type of notification or warning
///
- (void)recordingNotificationWithNotification:(enum RecordingProgressNotification)notification;
@end

/// Protocol defining settings-related events that clients can implement
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey19AppSettingsDelegate_")
@protocol AppSettingsDelegate
@optional
/// Called when the screen-on-while-recording setting changes
/// \param screenOn Indicates whether the screen should stay on while recording
///
- (void)isIdleTimerDisabledWithIsOn:(BOOL)screenOn;
/// Called when the appearance theme changes
/// \param uiTheme The new theme identifier
///
- (void)appearanceThemeChangedTo:(NSString * _Nonnull)uiTheme;
/// Called when the application language needs to be changed
/// \param languageCode Indicates configured UI or Application Locale value. Example: “en-US”, “es-US”
///
- (void)applicationLanguageChangedTo:(NSString * _Nonnull)languageCode;
@end

enum SignOutReason : NSInteger;
/// Protocol defining events for the TurnKey framework that clients can implement
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey13AppUiDelegate_")
@protocol AppUiDelegate
@optional
/// Called when the WebView finishes loading
/// \param isLoadingDone Indicates whether the web view has finished loading
///
- (void)webViewLoaded:(BOOL)isLoadingDone;
/// Notifies when a logout occurs
/// \param logoutType The reason for the logout (user initiated, inactivity, navigate away, or environment change)
///
- (void)logoutWith:(enum SignOutReason)logoutType;
@end

@class UIViewController;
SWIFT_CLASS("_TtC20DragonCopilotTurnkey27AppWebViewControllerWrapper")
@interface AppWebViewControllerWrapper : NSObject
- (UIViewController * _Nonnull)getViewController SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol ConfigurationProvider;
@protocol SessionDataProvider;
SWIFT_CLASS("_TtC20DragonCopilotTurnkey17ApplicationConfig")
@interface ApplicationConfig : NSObject
+ (ApplicationConfig * _Nonnull)getInstanceWithDataProvider:(id <ConfigurationProvider> _Nonnull)dataProvider delegate:(id <AppUiDelegate> _Nullable)delegate recordingDelegate:(id <AppRecordingDelegate> _Nullable)recordingDelegate dictationDelegate:(id <AppDictationDelegate> _Nullable)dictationDelegate settingsDelegate:(id <AppSettingsDelegate> _Nullable)settingsDelegate internalClientDelegate:(id <AppInternalDelegate> _Nullable)internalClientDelegate SWIFT_WARN_UNUSED_RESULT;
+ (void)clearInstance;
- (UIViewController * _Nonnull)openSessionControllerWithSessionDataProvider:(id <SessionDataProvider> _Nonnull)sessionDataProvider SWIFT_WARN_UNUSED_RESULT;
- (void)closeSession;
- (void)disableLogging;
- (void)developerModeWithIsON:(BOOL)isON;
+ (BOOL)isDeveloperModeOn SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ClientAppInfo;
@class ServerInfo;
enum AuthType : NSInteger;
@class UserInfo;
/// Configuration for the Turnkey SDK
SWIFT_CLASS("_TtC20DragonCopilotTurnkey25ApplicationConfigProvider")
@interface ApplicationConfigProvider : NSObject
/// Initializes a new instance of `ApplicationConfigProvider
- (nonnull instancetype)initWithClientAppInfo:(ClientAppInfo * _Nonnull)clientAppInfo serverInfo:(ServerInfo * _Nonnull)serverInfo providerName:(NSString * _Nonnull)providerName isInternalClient:(BOOL)isInternalClient authType:(enum AuthType)authType userInfo:(UserInfo * _Nullable)userInfo partnerId:(NSString * _Nullable)partnerId customerId:(NSString * _Nullable)customerId ehrInstanceId:(NSString * _Nullable)ehrInstanceId productId:(NSString * _Nullable)productId traceId:(NSString * _Nullable)traceId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Authentication type for the SDK
typedef SWIFT_ENUM(NSInteger, AuthType, open) {
  AuthTypeEntraId = 0,
  AuthTypePartnerToken = 1,
  AuthTypeSmartOnFhir = 2,
};

SWIFT_CLASS("_TtC20DragonCopilotTurnkey13ClientAppInfo")
@interface ClientAppInfo : NSObject
/// Initializes a new instance of <code>ClientAppInfo</code>.
- (nonnull instancetype)initWithAppId:(NSString * _Nullable)appId appVersion:(NSString * _Nullable)appVersion deviceId:(NSString * _Nullable)deviceId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Base class for token responses used in the Turnkey SDK.
/// \param token The access token string.
///
SWIFT_CLASS("_TtC20DragonCopilotTurnkey11ClientToken")
@interface ClientToken : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull token;
- (nonnull instancetype)initWithToken:(NSString * _Nonnull)token OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDate;
/// Token response for Entra authentication.
/// \param token The access token string.
///
/// \param expireOn The expiration date of the token.
///
/// \param scope Optional OAuth scopes for the token.
///
/// \param tenantId Optional Azure AD tenant identifier.
///
SWIFT_CLASS("_TtC20DragonCopilotTurnkey16ClientEntraToken")
@interface ClientEntraToken : ClientToken
@property (nonatomic, readonly, copy) NSDate * _Nonnull expireOn;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nullable scope;
@property (nonatomic, readonly, copy) NSString * _Nullable tenantId;
- (nonnull instancetype)initWithToken:(NSString * _Nonnull)token expireOn:(NSDate * _Nonnull)expireOn scope:(NSArray<NSString *> * _Nullable)scope tenantId:(NSString * _Nullable)tenantId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithToken:(NSString * _Nonnull)token SWIFT_UNAVAILABLE;
@end

/// Token response for SMART on FHIR (SoF) authentication.
/// Contains only the SMART launch parameters (issuer and launch).
/// The OAuth token is provided separately via ClientToken.
/// \param issuer The issuer URL for SMART on FHIR authentication.
///
/// \param launch The launch code for SMART on FHIR authentication.
///
SWIFT_CLASS("_TtC20DragonCopilotTurnkey14ClientSoFToken")
@interface ClientSoFToken : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull issuer;
@property (nonatomic, readonly, copy) NSString * _Nonnull launch;
- (nonnull instancetype)initWithIssuer:(NSString * _Nonnull)issuer launch:(NSString * _Nonnull)launch OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Container class to hold different types of authentication responses.
SWIFT_CLASS("_TtC20DragonCopilotTurnkey19ClientTokenProvider")
@interface ClientTokenProvider : NSObject
@property (nonatomic, readonly, strong) ClientToken * _Nullable clientToken;
@property (nonatomic, readonly, strong) ClientEntraToken * _Nullable clientEntraToken;
@property (nonatomic, readonly, strong) ClientSoFToken * _Nullable clientSoFToken;
/// Initializes the container with optional responses.
/// For SMART on FHIR, both clientToken (OAuth token) and clientSoFToken (SMART params) should be provided.
/// \param clientToken An instance of <code>ClientToken</code> or nil.
///
/// \param clientEntraToken An instance of <code>ClientEntraToken</code> or nil.
///
/// \param clientSoFToken An instance of <code>ClientSoFToken</code> or nil.
///
- (nonnull instancetype)initWithClientToken:(ClientToken * _Nullable)clientToken clientEntraToken:(ClientEntraToken * _Nullable)clientEntraToken clientSoFToken:(ClientSoFToken * _Nullable)clientSoFToken OBJC_DESIGNATED_INITIALIZER;
/// Convenience initializer for <code>ClientToken</code>.
/// \param clientToken An instance of <code>ClientToken</code>.
///
- (nonnull instancetype)initWithClientToken:(ClientToken * _Nonnull)clientToken;
/// Convenience initializer for <code>ClientEntraToken</code>.
/// \param clientEntraToken An instance of <code>ClientEntraToken</code>.
///
- (nonnull instancetype)initWithClientEntraToken:(ClientEntraToken * _Nonnull)clientEntraToken;
/// Convenience initializer for <code>ClientSoFToken</code>.
/// \param clientSoFToken An instance of <code>ClientSoFToken</code>.
///
- (nonnull instancetype)initWithClientSoFToken:(ClientSoFToken * _Nonnull)clientSoFToken;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Protocol for providing configuration data to the TurnKey framework
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey21ConfigurationProvider_")
@protocol ConfigurationProvider
/// Returns the configuration for the TurnKey framework
///
/// returns:
/// The configuration object
- (ApplicationConfigProvider * _Nonnull)getConfiguration SWIFT_WARN_UNUSED_RESULT;
/// Returns the access token provider for authentication
///
/// returns:
/// The access token provider
- (id <AppAccessTokenProvider> _Nonnull)getAccessTokenProvider SWIFT_WARN_UNUSED_RESULT;
/// Returns the user information
///
/// returns:
/// The user object
- (UserInfo * _Nonnull)getUserInfo SWIFT_WARN_UNUSED_RESULT;
@end

/// Represents details for a patient.
SWIFT_CLASS("_TtC20DragonCopilotTurnkey11PatientInfo")
@interface PatientInfo : NSObject
/// Initializes a new instance of <code>PatientInfo</code>.
- (nonnull instancetype)initWithId:(NSString * _Nullable)id fhirId:(NSString * _Nullable)fhirId firstName:(NSString * _Nullable)firstName lastName:(NSString * _Nullable)lastName middleName:(NSString * _Nullable)middleName gender:(NSString * _Nullable)gender birthDate:(NSDate * _Nullable)birthDate medicalRecordNumber:(NSString * _Nullable)medicalRecordNumber OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents different notifications and warnings during recording
typedef SWIFT_ENUM(NSInteger, RecordingProgressNotification, open) {
/// Warning that recording duration limit is approaching
  RecordingProgressNotificationReachedWarnLimit = 0,
/// Audio silence detected during recording
  RecordingProgressNotificationAudioLoss = 1,
/// External audio device detected
  RecordingProgressNotificationExternalAudioDeviceDetected = 2,
};

/// Represents the different reasons why a recording might be stopped
typedef SWIFT_ENUM(NSInteger, RecordingStopReason, open) {
/// User manually stopped recording
  RecordingStopReasonUser = 0,
/// Recording automatically stopped due to a system error
  RecordingStopReasonSystemError = 1,
/// Recording automatically stopped due to audio interruption (e.g., phone call)
  RecordingStopReasonAudioInterrupted = 2,
/// Recording automatically stopped because maximum duration was reached
  RecordingStopReasonReachedMaxLimit = 3,
/// Recording automatically stopped due to incompatible audio device detected
  RecordingStopReasonIncompatibleInputDevice = 4,
/// Recording automatically stopped due to audio device change
  RecordingStopReasonAudioDeviceChanged = 5,
};

/// SDK-level constants for default configuration values
SWIFT_CLASS("_TtC20DragonCopilotTurnkey12SDKConstants")
@interface SDKConstants : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC20DragonCopilotTurnkey10ServerInfo")
@interface ServerInfo : NSObject
/// Initializes a new instance of <code>ServerInfo</code>.
- (nonnull instancetype)initWithEnvironment:(NSString * _Nullable)environment geography:(NSString * _Nullable)geography cloudInstance:(NSString * _Nullable)cloudInstance OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class VisitInfo;
/// Protocol for providing session data to the TurnKey framework
SWIFT_PROTOCOL("_TtP20DragonCopilotTurnkey19SessionDataProvider_")
@protocol SessionDataProvider
/// Returns the patient information for the current session
///
/// returns:
/// The patient object
- (PatientInfo * _Nonnull)getPatientInfo SWIFT_WARN_UNUSED_RESULT;
/// Returns the visit information for the current session
///
/// returns:
/// The visit object
- (VisitInfo * _Nonnull)getVisitInfo SWIFT_WARN_UNUSED_RESULT;
@end

/// Represents the reason for user logout from the TurnKey framework
typedef SWIFT_ENUM(NSInteger, SignOutReason, open) {
/// User initiated logout
  SignOutReasonUser = 0,
/// Logout due to inactivity timeout
  SignOutReasonInactivity = 1,
/// Logout due to navigation away from the app
  SignOutReasonNavigateAway = 2,
/// Logout due to environment change
  SignOutReasonEnvironmentChange = 3,
/// Logout due to authentication failure
  SignOutReasonAuthenticationFailed = 4,
};

/// Represents details for a user or practitioner.
SWIFT_CLASS("_TtC20DragonCopilotTurnkey8UserInfo")
@interface UserInfo : NSObject
/// Initializes a new instance of <code>UserInfo</code>.
- (nonnull instancetype)initWithId:(NSString * _Nullable)id fhirId:(NSString * _Nullable)fhirId firstName:(NSString * _Nullable)firstName middleName:(NSString * _Nullable)middleName lastName:(NSString * _Nullable)lastName ehrUserId:(NSString * _Nullable)ehrUserId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents details of a visit.
SWIFT_CLASS("_TtC20DragonCopilotTurnkey9VisitInfo")
@interface VisitInfo : NSObject
/// Initializes a new instance of <code>VisitInfo</code>.
- (nonnull instancetype)initWithId:(NSString * _Nullable)id fhirId:(NSString * _Nullable)fhirId correlationId:(NSString * _Nullable)correlationId metadata:(NSString * _Nullable)metadata reasonForVisit:(NSString * _Nullable)reasonForVisit OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
